# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: SolarStations
author: AssessingSolar.org
logo: graphics/assessing_solar_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 240  # When to timeout each notebook in seconds
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    bibtex_reference_style: author_year
    bibtex_bibfiles: "references.bib"

# Information about where the book exists on the web
repository:
  url: https://github.com/assessingsolar/solarstations  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: graphics/assessing_solar_favicon.ico  # A path to a favicon image
  baseurl                   : https://SolarStations.Org
  analytics:
    google_analytics_id       : G-6KXSD7FTJM
