name: validate-csv

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  validate-csv:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install requests pandas numpy

      - name: Set up output matcher for PR annotations
        run: echo '::add-matcher::.github/workflows/validate-csv-matcher.json'

      - name: Check CSV data
        run: python .github/workflows/validate-csv.py
